ДЗ 5!
kirillpitsa/5sem_matprak pull request #3
Opened 2022-11-21 18:44 UTC by kirillpitsa

2022-11-21 18:49 UTC, kirillpitsa commented
Я не очень понимаю, что с расширением файла и откуда взялось _, поэтому в случае, если он не открывается:
https://colab.research.google.com/drive/161PK8JsM-i0gQB-AFKc6QNVDpif8kr5J?usp=sharing

2022-11-22 19:09 UTC, MathPracticum commented
удалите и перезагрузите файл по-новой с правильным расширением

2022-12-17 14:58 UTC, MathPracticum requested changes
доделать все задания

2022-12-26 17:37 UTC, MathPracticum approved these changes

2022-12-26 17:44 UTC, merged